---
linters:
  enable-all: true

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-rules:
    - path: challenge[36]\.go
      linters:
        - gomnd

    - path: _test\.go
      text: "Using the variable on range scope `tt` in function literal"

    - path: _test\.go
      linters:
        - funlen
        - gomnd
        - lll
        - wsl
